services:
  postgres:
    image: postgres:16
    container_name: postgre_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pet_project
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Brazilian_dataset:/data

volumes:
  pgdata: